version: '3.8'

services:
  nginx:
    build:
        context: ./.docker/nginx
        dockerfile: Dockerfile
    volumes:
      - ./:/app:delegated
    links:
      - php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./:/app:delegated
    restart: always
    #    env_file:
    #      - .env
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always

  mysql:
    image: mysql:8.0.28
    volumes:
      - .docker/dev-volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
